# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
